# LinearMath in Python with lib Numpy

## 1. Create Matrix

In [1]:
import numpy as np

# create matrix
arr = np.array([
    [2, 3, 5],
    [7, 11, 13],
    [17, 19, 23]
])
print(arr)

[[ 2  3  5]
 [ 7 11 13]
 [17 19 23]]


In [2]:
# another version of matrix
mtrx = np.matrix([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(mtrx)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## 2. Funcions of work with matrix

In [3]:
# транспонирование матрицы
A_t = mtrx.transpose()
print(A_t)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [4]:
# определитель матрицы
A_det = np.linalg.det(mtrx) # linalg - отдельный пакет
print(A_det)

-9.51619735392994e-16


In [5]:
# умножение матриц
new_A = arr.dot(mtrx)
print(new_A)

[[ 49  59  69]
 [142 173 204]
 [254 313 372]]


### 3rd task - inverse matrix

In [6]:
# обратная матрица
A_inv = np.linalg.inv(mtrx)
print(A_inv)

[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [7]:
# ранг матрицы
rank = np.linalg.matrix_rank(mtrx)
print(rank)

2


### 4th task - system of linear equations

In [8]:
# решение систем линейных уравнений
A = np.array([
    [2, 5],
    [1, -10]
])
V = np.array([1, 3])
X = np.linalg.solve(A, V)

In [9]:
print(X)

[ 1.  -0.2]


### 5th task - eigenvectors and eigenvalues

In [10]:
# собственные вектора и собственные значения
w,v = np.linalg.eig(arr)

In [11]:
print(w)

[36.81172799 -1.91702763  1.10529963]


In [12]:
print(v)

[[-0.16510917 -0.60574007  0.36952037]
 [-0.4789958  -0.3769456  -0.8244886 ]
 [-0.86214963  0.70070748  0.42857116]]


In [13]:
np.dot(arr, v)

array([[ -6.07795389,   1.16122046,   0.40843073],
       [-17.6326632 ,   0.72261513,  -0.91130695],
       [-31.73721763,  -1.3432756 ,   0.47369955]])

In [14]:
w*v

array([[ -6.07795389,   1.16122046,   0.40843073],
       [-17.6326632 ,   0.72261513,  -0.91130695],
       [-31.73721763,  -1.3432756 ,   0.47369955]])